Add: wireguard stuff to webdev.

diff --git a/proj/docker/webdev/Dockerfile b/proj/docker/webdev/Dockerfile
--- a/proj/docker/webdev/Dockerfile
+++ b/proj/docker/webdev/Dockerfile
@@ -1,6 +1,10 @@
 FROM ubuntu:20.04
 
-RUN apt update && apt install -y vim iproute2 iputils-ping tcpdump iptables dnsutils curl w3m dhcpcd5
+# So, installing resolvconf throws an error, which we don't care about. This error doesn't mean
+# the installation was a failure, it is just dumb. As such, we use echo to make the command always
+# succede (return 0). :D
+RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y -f vim iproute2 iputils-ping tcpdump dnsutils curl \
+  w3m dhcpcd5 wireguard resolvconf || echo
 
 COPY ./dhcpcd.conf /etc/dhcpcd.conf
 COPY ./entry.sh /entry.sh
